# grafana-service.yaml: Exposes Grafana as a Kubernetes Service
# Allows access to the Grafana UI for monitoring
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: go-k3-app-ns
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000