{
 "title": "App Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU % vs Memory (MB)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total[1m])) * 100",
     "legendFormat": "CPU %"
    },
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024",
     "legendFormat": "Memory (MB)"
    }
   ]
  },
  {
   "title": "Total Req/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(myapp_http_requests_total[1m]))",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "myapp_http_requests_total{job=\"go-k3-app\", path=\"/\"}",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Req Rate by Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(myapp_http_requests_total[5m])) by (path)"
    }
   ]
  },
  {
   "title": "90th Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(myapp_http_request_duration_seconds_bucket[5m])) by (le, path))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes / 1024 / 1024",
     "legendFormat": "Heap Allocated (MB)"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes / 1024 / 1024",
     "legendFormat": "Heap In Use (MB)"
    },
    {
     "expr": "go_memstats_heap_idle_bytes / 1024 / 1024",
     "legendFormat": "Heap Idle (MB)"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(process_network_transmit_bytes_total[1m])",
     "legendFormat": "Transmit"
    },
    {
     "expr": "rate(process_network_receive_bytes_total[1m])",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum[1m])/rate(go_gc_duration_seconds_count[1m])",
     "legendFormat": "GC Duration (avg)"
    },
    {
     "expr": "rate(go_gc_duration_seconds_count[1m])",
     "legendFormat": "GC Count (per sec)"
    }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(myapp_http_requests_total[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}