apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: go-k3-app-ns
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true 