# prom-service.yaml: Exposes Prometheus as a Kubernetes Service
# Allows access to Prometheus UI and metrics endpoints
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: go-k3-app-ns
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: ClusterIP